[package]
name = "graphene-application-io"
description = "graphene application io interface"
# Inherited from workspace - start
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true
# Inherited from workspace - end

[features]
default = ["serde"]
serde = ["dep:serde", "core-types/serde", "vector-types/serde", "text-nodes/serde", "graphene-resource/serde"]
wasm = ["dep:web-sys"]
wgpu = ["dep:raster-types", "raster-types/wgpu"]

[dependencies]
# Local dependencies
dyn-any = { workspace = true }
core-types = { workspace = true }
graphene-hash = { workspace = true, features = ["derive"] }
vector-types = { workspace = true }
text-nodes = { workspace = true }
graphene-resource = { workspace = true }

# Optional local dependencies
raster-types = { workspace = true, optional = true }

# Workspace dependencies
blake3 = { workspace = true }
glam = { workspace = true }
log = { workspace = true }

# Optional workspace dependencies
serde = { workspace = true, optional = true }
web-sys = { workspace = true, optional = true }
