// A public key generated by me (@0HyperCube) and restricted to the font api/
const fontListAPI = "https://api.graphite.rs/font-list";
let fontsList = [] as { family: string; variants: string[]; files: { [name: string]: string } }[];

fetch(fontListAPI)
	.then((response) => response.json())
	.then((json) => {
		fontsList = json.items;
	});

export function fontNames(): string[] {
	return fontsList.map((value) => value.family);
}

export function getFontVariants(name: string): string[] {
	const font = fontsList.find((value) => value.family === name);
	return font ? font.variants : [];
}

export function getFontFile(name: string, variant: string): string | undefined {
	const font = fontsList.find((value) => value.family === name);
	return font && font.files[variant].replace("http://", "https://");
}
