[package]
name = "dyn-any"
description = "An Any trait that works for arbitrary lifetimes"
version = "0.3.1"
license.workspace = true
authors.workspace = true
edition.workspace = true
documentation = "https://docs.rs/dyn-any"
repository = "https://github.com/GraphiteEditor/Graphite/tree/master/libraries/dyn-any"
readme = "./README.md"

[features]
default = ["std", "large-atomics"]
std = ["alloc", "rc", "glam/default"]
large-atomics = []
alloc = []
derive = ["dyn-any-derive"]
log-bad-types = []
# Opt into impls for Rc<T> and Arc<T>.
rc = []
# Opt into impls for some glam types
glam = ["dep:glam"]

[dependencies]
# Optional local dependencies
dyn-any-derive = { path = "derive", optional = true }

# Optional dependencies
glam = { version = "0.32.1", optional = true, default-features = false }
reqwest = { version = "0.13", optional = true, default-features = false }

[package.metadata.docs.rs]
all-features = true
