[package]
name = "dyn-any-derive"
description = "#[derive(DynAny)]"
version = "0.3.0"
license.workspace = true
authors.workspace = true
edition.workspace = true
documentation = "https://docs.rs/dyn-any-derive"
repository = "https://github.com/GraphiteEditor/Graphite/tree/master/libraries/dyn-any/derive"
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
# Workspace dependencies
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
# Local dependencies
dyn-any = { path = "..", features = ["derive"] }
