[package]
name = "raster-nodes-shaders"
description = "graphene raster data format"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
readme.workspace = true
homepage.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]

[build-dependencies]
cargo-gpu-install = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
