[package]
name = "brush-types"
version = "0.1.0"
edition = "2024"
description = "The brush stroke data format for Graphene"
authors = ["Graphite Authors <contact@graphite.art>"]
license = "MIT OR Apache-2.0"

[features]
default = ["serde"]
serde = ["dep:serde", "core-types/serde"]

[dependencies]
# Local dependencies
core-types = { workspace = true }
graphene-hash = { workspace = true }

# Workspace dependencies
dyn-any = { workspace = true }
glam = { workspace = true }

# Optional workspace dependencies
serde = { workspace = true, optional = true }
