[package]
name = "graphene-core-shaders"
version = "0.1.0"
edition = "2024"
description = "no_std API definitions for Graphene"
authors = ["Graphite Authors <contact@graphite.rs>"]
license = "MIT OR Apache-2.0"

[features]
# any feature that
# * must be usable in shaders
# * but requires std
# * and should be on by default
# should be in this list instead of `[workspace.dependency]`
std = [
	"dep:dyn-any",
	"dep:serde",
	"dep:specta",
	"dep:log",
	"glam/debug-glam-assert",
	"glam/std",
	"glam/serde",
	"half/std",
	"half/serde",
	"num-traits/std",
	"num_enum/std",
]

[dependencies]
# Local dependencies
node-macro = { workspace = true }

# Local std dependencies
dyn-any = { workspace = true, optional = true }

# Workspace dependencies
bytemuck = { workspace = true }
glam = { workspace = true }
half = { workspace = true, default-features = false }
num-derive = { workspace = true }
num-traits = { workspace = true }
num_enum = { workspace = true }
spirv-std = { workspace = true }

# Workspace std dependencies
serde = { workspace = true, optional = true }
specta = { workspace = true, optional = true }
log = { workspace = true, optional = true }

[dev-dependencies]
graphene-core = { workspace = true }

[lints.rust]
# the spirv target is not in the list of common cfgs so must be added manually
unexpected_cfgs = { level = "warn", check-cfg = [
	'cfg(target_arch, values("spirv"))',
] }

[package.metadata.cargo-shear]
ignored = ["graphene-core"]
