//! Generator of Lorem Ipsum placeholder text from a bigram Markov chain built from Cicero's "De finibus bonorum et malorum",
//! the Latin work the traditional passage was scrambled from. The build script reduces the corpus to a vocabulary and a stream
//! of word indices, which are indexed by bigram at first use so each bigram is followed as it was in the corpus.

use std::sync::OnceLock;

// Generated by build.rs: TOKENS, VOCABULARY, VOCABULARY_LEN
include!(concat!(env!("OUT_DIR"), "/corpus_data.rs"));

/// The classic Lorem Ipsum placeholder text (1 paragraph, 4 sentences, 69 words).
pub const CLASSIC_TEXT: &str = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

/// Punctuation characters that end sentences and clauses.
const SENTENCE_ENDERS: [char; 3] = ['.', '!', '?'];
const CLAUSE_ENDERS: [char; 3] = [',', ';', ':'];

/// Each paragraph draws a length in words uniformly from this range and ends at the first sentence end at or past it.
const PARAGRAPH_WORDS: std::ops::RangeInclusive<usize> = 15..=100;

/// Sentence length in words past which the chain prefers a continuation that ends the sentence, when the corpus offers one.
const PREFERRED_MAX_SENTENCE_WORDS: usize = 30;

/// Sentence length in words past which the next clause boundary ends the sentence, since Cicero's sentences can pass 100 words.
const HARD_MAX_SENTENCE_WORDS: usize = 50;

/// A three-word phrase is not repeated within this many words if the corpus offers another continuation, which keeps the chain from looping.
const REPETITION_WINDOW: usize = 40;

/// When the text has to be closed mid-sentence, clause punctuation is only kept if at least this many words follow it.
const MIN_WORDS_AFTER_CLAUSE_BREAK: usize = 3;

/// A paragraph break is only written once at least this many words follow it, so the text never ends on a stub of a paragraph.
const MIN_WORDS_AFTER_PARAGRAPH_BREAK: usize = 8;

/// Unit of measurement for the length of an opener or total output.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Unit {
	Characters,
	Words,
	Sentences,
	Paragraphs,
}

/// Generates Lorem Ipsum placeholder text: a prefix of the classic passage sized by `opener_length` in `opener_unit`,
/// continued by the Markov chain until the whole output reaches `total_length` in `total_unit`.
///
/// The output always ends with a sentence end. A length in Characters is never exceeded, but may fall short since only
/// whole words are used. An opener in Paragraphs is a paragraph of its own, and any other opener counts toward the first
/// paragraph without being split by it. An opener cut off mid-sentence is closed as a sentence of its own.
///
/// The words depend only on the values returned by `rand_index` (given `n`, a uniformly random index in `0..n`),
/// never on the lengths or units, so a longer length only extends the text of a shorter one.
#[must_use]
pub fn generate(opener_length: usize, opener_unit: Unit, total_length: usize, total_unit: Unit, mut rand_index: impl FnMut(usize) -> usize) -> String {
	let corpus = corpus();
	if total_length == 0 || corpus.sentence_starts.is_empty() {
		return String::new();
	}

	let paragraph_lengths = ParagraphLengths(rand_index(u32::MAX as usize) as u64);
	let mut out = Output::new(corpus, total_length, total_unit, paragraph_lengths);

	out.emit_opener(opener_length, opener_unit);
	out.ensure_sentence_end();

	if opener_unit == Unit::Paragraphs && opener_length > 0 {
		// The classic paragraph is complete whatever length was drawn for it
		let complete = if total_unit == Unit::Paragraphs { total_length == 1 } else { out.is_complete() };
		if complete {
			return out.finish();
		}
		out.push_paragraph_break();
	} else {
		out.maybe_push_paragraph_break();
	}
	if out.is_complete() {
		return out.finish();
	}

	// The iteration cap only guards against a corpus edit that leaves the chain unable to reach a sentence end
	let mut state = out.restart(&mut rand_index);
	let max_iterations = total_length.saturating_add(1).saturating_mul(2000);
	for _ in 0..max_iterations {
		if out.is_complete() {
			break;
		}
		let Some((prev, curr)) = state else { break };

		let occurrences = corpus.occurrences_of(prev, curr);
		if occurrences.is_empty() {
			// Only the corpus's final bigram is never followed by a word, so close the sentence and start a fresh one
			out.ensure_sentence_end();
			if out.is_complete() {
				break;
			}
			out.maybe_push_paragraph_break();
			state = out.restart(&mut rand_index);
			continue;
		}

		let next = out.pick_next(prev, curr, occurrences, &mut rand_index);
		out.push_chain_word(next);
		out.maybe_push_paragraph_break();
		state = Some((curr, next));
	}

	out.finish()
}

// ============
// Output state
// ============

struct Output {
	corpus: &'static Corpus,
	total_length: usize,
	total_unit: Unit,
	text: String,
	words: usize,
	sentences: usize,
	paragraph_breaks: usize,
	/// Chain words in the current sentence. The opener is not counted, so it never changes which words follow it.
	words_in_current_sentence: usize,
	words_in_current_paragraph: usize,
	/// Drawn length (in words) of the paragraph being written.
	target_paragraph_words: usize,
	paragraph_lengths: ParagraphLengths,
	/// The last `REPETITION_WINDOW` chain words, as vocabulary indices.
	recent_words: Vec<u16>,
}

impl Output {
	fn new(corpus: &'static Corpus, total_length: usize, total_unit: Unit, mut paragraph_lengths: ParagraphLengths) -> Self {
		Self {
			corpus,
			total_length,
			total_unit,
			text: String::new(),
			words: 0,
			sentences: 0,
			paragraph_breaks: 0,
			words_in_current_sentence: 0,
			words_in_current_paragraph: 0,
			target_paragraph_words: paragraph_lengths.next(),
			paragraph_lengths,
			recent_words: Vec::with_capacity(REPETITION_WINDOW + 1),
		}
	}

	/// Whether the requested length has been reached. A paragraph count is only reached once the final paragraph is full,
	/// so it never ends as a stub. A character count is overshot so `finish` can choose the cut.
	fn is_complete(&self) -> bool {
		match self.total_unit {
			Unit::Characters => self.text.len() > self.total_length,
			Unit::Words => self.words >= self.total_length,
			Unit::Sentences => self.sentences >= self.total_length,
			Unit::Paragraphs => self.paragraph_breaks + 1 >= self.total_length && self.paragraph_full(),
		}
	}

	fn paragraph_full(&self) -> bool {
		self.words_in_current_paragraph >= self.target_paragraph_words && self.text.ends_with(SENTENCE_ENDERS)
	}

	/// Emits the requested prefix of the classic passage, whole words only, stopping early if the total is reached.
	fn emit_opener(&mut self, opener_length: usize, opener_unit: Unit) {
		if opener_length == 0 {
			return;
		}

		let word_count = match opener_unit {
			Unit::Characters => {
				// The opener is measured closed, as `finish` measures the whole text
				let word_ends = CLASSIC_TEXT.match_indices(' ').map(|(index, _)| index).chain([CLASSIC_TEXT.len()]);
				word_ends.take_while(|&word_end| closed(&CLASSIC_TEXT[..word_end]).len() <= opener_length).count()
			}
			Unit::Words => opener_length,
			Unit::Sentences => CLASSIC_TEXT
				.split_inclusive(SENTENCE_ENDERS)
				.take(opener_length)
				.map(|sentence| sentence.split_whitespace().count())
				.sum(),
			Unit::Paragraphs => usize::MAX,
		};

		for word in CLASSIC_TEXT.split_whitespace().take(word_count) {
			// A paragraph count is not checked, since the passage could fill the first paragraph partway through
			if self.total_unit != Unit::Paragraphs && self.is_complete() {
				break;
			}

			self.push_token(word);
			self.words_in_current_paragraph += 1;
		}
	}

	/// Starts a fresh sentence from a random sentence opening of the corpus, emitting its two words.
	/// Returns the bigram to continue from, or `None` once the output is complete.
	fn restart(&mut self, rand_index: &mut impl FnMut(usize) -> usize) -> Option<(u16, u16)> {
		let position = self.corpus.sentence_starts[rand_index(self.corpus.sentence_starts.len())] as usize;
		let (a, b) = (TOKENS[position], TOKENS[position + 1]);

		self.push_chain_word(a);
		if self.is_complete() {
			return None;
		}
		self.push_chain_word(b);

		Some((a, b))
	}

	/// Picks the word following one of the bigram's occurrences, so each is weighted by how often the corpus has it.
	/// Words that repeat a recent phrase are skipped, and an overlong sentence prefers a word that ends it.
	fn pick_next(&self, prev: u16, curr: u16, occurrences: &[u16], rand_index: &mut impl FnMut(usize) -> usize) -> u16 {
		let mut candidates: Vec<u16> = occurrences.iter().map(|&position| successor(position)).collect();

		let repeats_recent_phrase = |next: u16| self.recent_words.windows(3).any(|phrase| phrase == [prev, curr, next]);
		if candidates.iter().any(|&word| !repeats_recent_phrase(word)) {
			candidates.retain(|&word| !repeats_recent_phrase(word));
		}

		let ends_sentence = |word: u16| self.corpus.word(word).ends_with(SENTENCE_ENDERS);
		let past_preferred_max = self.words_in_current_sentence >= PREFERRED_MAX_SENTENCE_WORDS;
		if past_preferred_max && candidates.iter().any(|&word| ends_sentence(word)) {
			candidates.retain(|&word| ends_sentence(word));
		}

		candidates[rand_index(candidates.len())]
	}

	/// Pushes a chain word. Past the hard sentence cap, a word ending in a clause boundary is pushed as a sentence end instead.
	fn push_chain_word(&mut self, word: u16) {
		let token = self.corpus.word(word);
		let past_hard_max = self.words_in_current_sentence >= HARD_MAX_SENTENCE_WORDS;

		self.words_in_current_sentence += 1;
		self.words_in_current_paragraph += 1;
		if past_hard_max && token.ends_with(CLAUSE_ENDERS) {
			self.push_token(&format!("{}.", token.trim_end_matches(CLAUSE_ENDERS)));
		} else {
			self.push_token(token);
		}

		self.recent_words.push(word);
		if self.recent_words.len() > REPETITION_WINDOW {
			self.recent_words.remove(0);
		}
	}

	/// Appends a token with its preceding space, capitalizing it after a sentence end or paragraph break since the vocabulary is all lowercase.
	fn push_token(&mut self, token: &str) {
		let capitalize = self.text.is_empty() || self.text.ends_with('\n') || self.text.ends_with(SENTENCE_ENDERS);
		if !self.text.is_empty() && !self.text.ends_with('\n') {
			self.text.push(' ');
		}

		if capitalize {
			let mut chars = token.chars();
			if let Some(first) = chars.next() {
				self.text.extend(first.to_uppercase());
				self.text.push_str(chars.as_str());
			}
		} else {
			self.text.push_str(token);
		}

		self.words += 1;
		if token.ends_with(SENTENCE_ENDERS) {
			self.sentences += 1;
			self.words_in_current_sentence = 0;
		}
	}

	/// Closes the current sentence if it is still open.
	fn ensure_sentence_end(&mut self) {
		if self.text.is_empty() || self.text.ends_with('\n') || self.text.ends_with(SENTENCE_ENDERS) {
			return;
		}

		self.text = closed(&self.text);
		self.sentences += 1;
		self.words_in_current_sentence = 0;
	}

	/// Starts a new paragraph of a newly drawn length. Text measured in Characters is typically inline copy, so there the break is not written.
	fn push_paragraph_break(&mut self) {
		if !self.text.is_empty() && !self.text.ends_with('\n') && self.total_unit != Unit::Characters {
			self.text.push('\n');
		}
		self.paragraph_breaks += 1;
		self.words_in_current_paragraph = 0;
		self.target_paragraph_words = self.paragraph_lengths.next();
	}

	/// Ends the paragraph once it has reached its drawn length, unless the text is complete.
	fn maybe_push_paragraph_break(&mut self) {
		if self.paragraph_full() && !self.is_complete() {
			self.push_paragraph_break();
		}
	}

	/// The text closed with a sentence end, and in Characters mode cut after the last word that lets it fit the length.
	fn finish(mut self) -> String {
		if self.total_unit != Unit::Characters {
			// Only the last break can have too few words after it, and until it has enough it is written as a space
			let text_end = self.text.trim_end_matches('\n').len();
			if let Some(last_break) = self.text[..text_end].rfind('\n')
				&& self.text[last_break..text_end].split_whitespace().count() < MIN_WORDS_AFTER_PARAGRAPH_BREAK
			{
				self.text.replace_range(last_break..=last_break, " ");
			}

			return closed(&self.text);
		}

		// Closing the text can shorten it (dropped clause marks) or lengthen it (the period), so each cut is measured closed
		let mut word_end = self.text.len();
		loop {
			let candidate = closed(&self.text[..word_end]);
			if candidate.len() <= self.total_length {
				return candidate;
			}

			let Some(previous_word_end) = self.text[..word_end].rfind(' ') else { return String::new() };
			word_end = previous_word_end;
		}
	}
}

/// The text with a sentence left open at its end closed by a period. Clause punctuation followed by fewer than
/// `MIN_WORDS_AFTER_CLAUSE_BREAK` words is dropped along the way, so the text never ends on a stranded fragment like ", de."
fn closed(text: &str) -> String {
	let mut closed = text.trim_end_matches('\n').to_owned();
	if closed.is_empty() || closed.ends_with(SENTENCE_ENDERS) {
		return closed;
	}

	// Walk back over the last words of the open sentence, dropping the punctuation that trails each
	let mut word_end = closed.len();
	for _ in 0..MIN_WORDS_AFTER_CLAUSE_BREAK {
		let trimmed_end = closed[..word_end].trim_end_matches(|c: char| c.is_ascii_punctuation()).len();
		closed.replace_range(trimmed_end..word_end, "");

		let Some(previous_word_end) = closed[..trimmed_end].rfind([' ', '\n']) else { break };
		if closed[..previous_word_end].ends_with(SENTENCE_ENDERS) {
			break;
		}
		word_end = previous_word_end;
	}

	closed.push('.');
	closed
}

/// Paragraph lengths come from a generator of their own (SplitMix64), so that paragraphing never disturbs the choice of words.
struct ParagraphLengths(u64);

impl ParagraphLengths {
	/// A length in words drawn uniformly from `PARAGRAPH_WORDS`.
	fn next(&mut self) -> usize {
		self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
		let mut mixed = self.0;
		mixed = (mixed ^ (mixed >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
		mixed = (mixed ^ (mixed >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
		mixed ^= mixed >> 31;

		let span = (PARAGRAPH_WORDS.end() - PARAGRAPH_WORDS.start() + 1) as u64;
		PARAGRAPH_WORDS.start() + (mixed % span) as usize
	}
}

// ======
// Corpus
// ======

/// The corpus in the form the chain walks: a decoded vocabulary plus an index of where each bigram occurs.
struct Corpus {
	/// All vocabulary words concatenated, delimited by `word_offsets`.
	words: String,
	word_offsets: Vec<u32>,
	/// Every corpus position that has a successor (all but the last two), sorted by the bigram that starts there and then by position,
	/// so that a bigram's occurrences form one contiguous run.
	positions_by_bigram: Vec<u16>,
	/// The corpus positions that begin a sentence and have a successor, used to (re)start the chain.
	sentence_starts: Vec<u16>,
}

/// Builds the corpus index on first use (about 250 KB of permanently allocated heap and a few milliseconds).
fn corpus() -> &'static Corpus {
	static CORPUS: OnceLock<Corpus> = OnceLock::new();
	CORPUS.get_or_init(Corpus::build)
}

impl Corpus {
	fn build() -> Self {
		// Each front-coded entry is the length of the prefix shared with the previous word, the suffix length, then the suffix
		let mut words: Vec<u8> = Vec::with_capacity(VOCABULARY.len() * 2);
		let mut word_offsets: Vec<u32> = Vec::with_capacity(VOCABULARY_LEN + 1);
		let mut cursor = 0;
		while cursor + 2 <= VOCABULARY.len() {
			let shared = VOCABULARY[cursor] as usize;
			let suffix_length = VOCABULARY[cursor + 1] as usize;
			let previous_start = word_offsets.last().map_or(0, |&offset| offset as usize);

			word_offsets.push(words.len() as u32);
			words.extend_from_within(previous_start..previous_start + shared);
			words.extend_from_slice(&VOCABULARY[cursor + 2..cursor + 2 + suffix_length]);
			cursor += 2 + suffix_length;
		}
		word_offsets.push(words.len() as u32);
		let words = String::from_utf8(words).expect("The vocabulary is ASCII");

		// Ties broken by position make the order, and so the generated text, independent of the sort algorithm
		let position_count = TOKENS.len().saturating_sub(2) as u16;
		let mut positions_by_bigram: Vec<u16> = (0..position_count).collect();
		positions_by_bigram.sort_unstable_by_key(|&position| (bigram_key(position), position));

		let mut corpus = Self {
			words,
			word_offsets,
			positions_by_bigram,
			sentence_starts: Vec::new(),
		};

		let starts_sentence = |&position: &u16| position == 0 || corpus.word(TOKENS[position as usize - 1]).ends_with(SENTENCE_ENDERS);
		corpus.sentence_starts = (0..position_count).filter(starts_sentence).collect();

		// The index is never freed, so its spare capacity is released
		corpus.words.shrink_to_fit();
		corpus.sentence_starts.shrink_to_fit();

		corpus
	}

	fn word(&self, index: u16) -> &str {
		&self.words[self.word_offsets[index as usize] as usize..self.word_offsets[index as usize + 1] as usize]
	}

	/// The corpus positions where the bigram occurs followed by another word, in O(log n).
	fn occurrences_of(&self, prev: u16, curr: u16) -> &[u16] {
		let key = (prev as u32) << 16 | curr as u32;
		let start = self.positions_by_bigram.partition_point(|&position| bigram_key(position) < key);
		let length = self.positions_by_bigram[start..].partition_point(|&position| bigram_key(position) == key);
		&self.positions_by_bigram[start..start + length]
	}
}

fn bigram_key(position: u16) -> u32 {
	let position = position as usize;
	(TOKENS[position] as u32) << 16 | TOKENS[position + 1] as u32
}

/// The word that followed the bigram at this corpus position.
fn successor(position: u16) -> u16 {
	TOKENS[position as usize + 2]
}

#[cfg(test)]
mod tests;
