// Generated by build.rs:
// SENTENCE_ENDERS, WORD_DATA, WORD_OFFSETS, STARTERS, SINGLE_KEYS, SINGLE_VALUES, MULTI_KEYS, MULTI_STARTS, SUCCESSORS, CLASSIC_LOREM_IPSUM_TEXT, CLASSIC_WORD_INDICES
include!(concat!(env!("OUT_DIR"), "/chain_data.rs"));

/// The classic Lorem Ipsum placeholder text (1 paragraph, 4 sentences, 69 words).
pub const CLASSIC_TEXT: &str = CLASSIC_LOREM_IPSUM_TEXT;

/// Unit of measurement for the length of an opener or total output.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Unit {
	Characters,
	Words,
	Sentences,
	Paragraphs,
}

/// Generates Lorem Ipsum placeholder text using a bigram Markov chain trained on Cicero's
/// classical Latin corpus (the original source of the Lorem Ipsum passage).
///
/// The output has two parts: an opener — a verbatim prefix of the traditional Lorem Ipsum
/// text, sized by `opener_length` counted in `opener_unit` — and a continuation generated
/// by the Markov chain until the combined output reaches `total_length` in `total_unit`.
///
/// Paragraph lengths are pre-rolled from a truncated geometric distribution: single-sentence
/// paragraphs have a 1/10 chance, and from the second sentence onward each has a 1/3 chance
/// of ending the paragraph, with a hard cap at 10 sentences (enforced via rejection sampling
/// to keep the PMF monotonically decreasing). This produces a mean of ~3.5 and median of 3
/// sentences per paragraph, matching the profile of modern English body text.
///
/// When `opener_unit` is Paragraphs, the classic text forms its own complete paragraph:
/// 0 = no opener, 1+ = classic text followed by a paragraph break before the continuation.
/// Other opener units (Words, Sentences, Characters) flow inline with the continuation.
///
/// `rand_index` is a closure that, given `n`, returns a uniformly random index in `0..n`.
#[must_use]
pub fn generate(opener_length: usize, opener_unit: Unit, total_length: usize, total_unit: Unit, mut rand_index: impl FnMut(usize) -> usize) -> String {
	if total_length == 0 || STARTERS.is_empty() {
		return String::new();
	}

	let mut out = Output::new();
	out.target_paragraph_sentences = sample_paragraph_length(&mut rand_index);

	let opener_words_used = emit_opener(&mut out, opener_length, opener_unit);

	// When the opener unit is Paragraphs, the classic text forms its own complete paragraph.
	// A value of 1+ appends a paragraph break so the continuation starts on a fresh paragraph.
	// Other opener units (Words, Sentences, Characters) flow inline with the continuation
	let opener_ended_with_break = opener_unit == Unit::Paragraphs && opener_length >= 1 && opener_words_used > 0;
	if opener_ended_with_break {
		out.push_paragraph_break();
		out.target_paragraph_sentences = sample_paragraph_length(&mut rand_index);
	}

	// For Paragraphs unit, the opener's paragraph break counts toward the total, so if the
	// opener already completed enough paragraphs we can stop. For other units, a simple
	// measurement check suffices
	if total_unit == Unit::Paragraphs {
		if opener_ended_with_break && out.paragraph_breaks >= total_length {
			// Strip the trailing '\n' since the final paragraph shouldn't end with one
			if out.output.ends_with('\n') {
				out.output.pop();
			}
			return out.output;
		}
	} else if out.measure(total_unit) >= total_length {
		truncate_to_target(&mut out, total_length, total_unit);
		apply_endgame(&mut out.output, total_unit);
		return out.output;
	}

	let (mut prev, mut curr) = seed_chain(&mut out, opener_words_used, opener_ended_with_break, &mut rand_index);

	// Main continuation loop. The chain emits one word per step. Paragraph breaks are not part
	// of the chain's vocabulary; instead they are inserted stochastically at sentence boundaries
	// using a geometric distribution. Build-time cycle detection ensures every reachable state
	// can eventually reach a dead end, so this loop is guaranteed to terminate naturally
	let max_iterations = (total_length + 1).saturating_mul(2000);
	for _ in 0..max_iterations {
		// Pre-emit stop check
		if out.measure(total_unit) >= total_length {
			break;
		}

		let followers = successors_of(prev, curr);
		if followers.is_empty() {
			// Dead end: the corpus had no continuations for this bigram (or build-time pruning
			// removed cycle-only successors). Ensure we're at a clean sentence boundary before
			// reseeding so the output doesn't break mid-thought without punctuation
			ensure_sentence_end(&mut out);

			// The forced sentence end might have completed the target
			if out.measure(total_unit) >= total_length {
				break;
			}

			// Paragraph break if the current paragraph has reached its pre-rolled target length
			if total_unit != Unit::Characters && out.sentences_in_current_paragraph >= out.target_paragraph_sentences && out.measure(total_unit) < total_length {
				out.push_paragraph_break();
				out.target_paragraph_sentences = sample_paragraph_length(&mut rand_index);
			}

			let (a, b) = starter_bigram(STARTERS[rand_index(STARTERS.len())]);
			prev = a;
			curr = b;
			if !try_push_token(&mut out, word(a), total_length, total_unit) {
				break;
			}
			if !try_push_token(&mut out, word(b), total_length, total_unit) {
				break;
			}
			continue;
		}

		// For the Words unit's final real word, prefer a successor that ends a sentence so the
		// output terminates cleanly. Fall back to force-append of a period in apply_endgame
		let at_final_word = total_unit == Unit::Words && out.words + 1 == total_length;
		let next = pick_next(followers, at_final_word, total_unit, &out, total_length, &mut rand_index);

		if !try_push_token(&mut out, word(next), total_length, total_unit) {
			break;
		}

		// Paragraph break if the sentence just emitted completes the current paragraph's target.
		// In Characters mode, the '\n' byte would unpredictably eat into the exact byte budget,
		// so paragraph breaks are skipped (character-counted text is typically inline anyway)
		if total_unit != Unit::Characters && word(next).ends_with(SENTENCE_ENDERS) && out.sentences_in_current_paragraph >= out.target_paragraph_sentences && out.measure(total_unit) < total_length {
			out.push_paragraph_break();
			out.target_paragraph_sentences = sample_paragraph_length(&mut rand_index);
		}

		prev = curr;
		curr = next;
	}

	// The seed bigram from seed_chain may overshoot a small Characters budget since it emits
	// two words unconditionally. Truncate before applying endgame so the final length is exact
	if total_unit == Unit::Characters && out.output.len() > total_length {
		truncate_to_target(&mut out, total_length, total_unit);
	}

	// When the main loop ends a few bytes short of the Characters target (e.g. the last word
	// fit but left a gap too small for another word+space), pad with periods to hit the exact
	// requested length before applying endgame
	if total_unit == Unit::Characters && out.output.len() < total_length {
		let deficit = total_length - out.output.len();
		for _ in 0..deficit {
			out.output.push('.');
		}
	}

	apply_endgame(&mut out.output, total_unit);
	out.output
}

// ============
// Output state
// ============

struct Output {
	output: String,
	words: usize,
	sentences: usize,
	paragraph_breaks: usize,
	sentences_in_current_paragraph: usize,
	/// Pre-rolled target length (in sentences) for the current paragraph, sampled from a
	/// truncated geometric distribution via rejection sampling
	target_paragraph_sentences: usize,
}

impl Output {
	fn new() -> Self {
		Self {
			output: String::new(),
			words: 0,
			sentences: 0,
			paragraph_breaks: 0,
			sentences_in_current_paragraph: 0,
			target_paragraph_sentences: 0,
		}
	}

	/// Append a word token to the output with preceding space. Words following a sentence-ender
	/// or paragraph break are capitalized automatically, since the training corpus is lowercased
	/// during preprocessing.
	fn push_token(&mut self, token: &str) {
		let capitalize = self.output.is_empty() || self.output.ends_with('\n') || self.output.ends_with(SENTENCE_ENDERS);

		if !self.output.is_empty() && !self.output.ends_with('\n') && !self.output.ends_with(' ') {
			self.output.push(' ');
		}

		if capitalize {
			let mut chars = token.chars();
			if let Some(first) = chars.next() {
				self.output.extend(first.to_uppercase());
				self.output.push_str(chars.as_str());
			}
		} else {
			self.output.push_str(token);
		}

		self.words += 1;
		if token.ends_with(SENTENCE_ENDERS) {
			self.sentences += 1;
			self.sentences_in_current_paragraph += 1;
		}
	}

	fn push_paragraph_break(&mut self) {
		if !self.output.ends_with('\n') && !self.output.is_empty() {
			self.output.push('\n');
			self.paragraph_breaks += 1;
			self.sentences_in_current_paragraph = 0;
		}
	}

	fn measure(&self, unit: Unit) -> usize {
		match unit {
			Unit::Characters => self.output.len(),
			Unit::Words => self.words,
			Unit::Sentences => self.sentences,
			Unit::Paragraphs => {
				if self.words == 0 {
					0
				} else if self.output.ends_with('\n') {
					self.paragraph_breaks
				} else {
					self.paragraph_breaks + 1
				}
			}
		}
	}
}

// ===============
// Opener emission
// ===============

fn emit_opener(out: &mut Output, opener_length: usize, opener_unit: Unit) -> usize {
	if opener_length == 0 {
		return 0;
	}

	// For Characters, emit the exact requested number of characters from the classic text
	// rather than rounding to whole words. Only complete words (those followed by a space or
	// at the end of the classic text) are counted in the bookkeeping so that partial trailing
	// fragments don't inflate the word/sentence counts or mislead seed_chain
	if opener_unit == Unit::Characters {
		let end = CLASSIC_LOREM_IPSUM_TEXT.floor_char_boundary(opener_length.min(CLASSIC_LOREM_IPSUM_TEXT.len()));
		let prefix = &CLASSIC_LOREM_IPSUM_TEXT[..end];
		out.output.push_str(prefix);

		// Determine how many complete classic words fit within the prefix. A word is complete
		// if the character after it in the full classic text is whitespace (or it's the last word)
		let classic: Vec<&str> = CLASSIC_LOREM_IPSUM_TEXT.split_whitespace().collect();
		let mut char_pos = 0;
		let mut complete_words = 0;
		for &word in &classic {
			let word_end = char_pos + word.len();
			if word_end > end {
				break;
			}
			complete_words += 1;
			out.words += 1;
			if word.ends_with(SENTENCE_ENDERS) {
				out.sentences += 1;
			}
			// Skip past the word and the space after it
			char_pos = word_end + 1;
		}

		return complete_words;
	}

	let classic: Vec<&str> = CLASSIC_LOREM_IPSUM_TEXT.split_whitespace().collect();
	let words_to_emit = match opener_unit {
		Unit::Words => opener_length.min(classic.len()),
		Unit::Sentences => {
			let mut sentences_seen = 0;
			let mut words_for_sentences = classic.len();
			for (i, w) in classic.iter().enumerate() {
				if w.ends_with(SENTENCE_ENDERS) {
					sentences_seen += 1;
					if sentences_seen >= opener_length {
						words_for_sentences = i + 1;
						break;
					}
				}
			}
			words_for_sentences
		}
		Unit::Paragraphs => classic.len(),  // 1 or 2 both emit the full classic text; 0 is handled by caller
		Unit::Characters => unreachable!(), // We handle Characters separately above
	};

	for &w in classic.iter().take(words_to_emit) {
		out.push_token(w);
	}

	words_to_emit
}

// =============
// Chain seeding
// =============

/// Returns the bigram from which the Markov chain should walk next. If the bigram is a fresh
/// random starter (not already present in the output), its two words are also emitted so the
/// new paragraph's opening is in the output and the chain walks forward from there.
fn seed_chain(out: &mut Output, opener_words_used: usize, opener_ended_with_break: bool, rand_index: &mut impl FnMut(usize) -> usize) -> (u16, u16) {
	// When the opener contributed a usable tail bigram that has successors in the transition
	// table, continue straight from it. The classic text isn't part of the training corpus, so
	// not every classic bigram will be productive — skip any that would be immediate dead ends
	if !opener_ended_with_break && opener_words_used >= 2 {
		for i in (0..opener_words_used - 1).rev() {
			let (a, b) = (CLASSIC_WORD_INDICES[i], CLASSIC_WORD_INDICES[i + 1]);
			if a != u16::MAX && b != u16::MAX && !successors_of(a, b).is_empty() {
				return (a, b);
			}
		}
	}

	// Fresh start: pick a random starter and emit both words so the chain's opening bigram
	// is present in the output
	let (a, b) = starter_bigram(STARTERS[rand_index(STARTERS.len())]);
	out.push_token(word(a));
	out.push_token(word(b));
	(a, b)
}

// =================
// Main-loop helpers
// =================

/// Pick the next successor for this step, applying unit-specific biasing.
fn pick_next(followers: &[u16], at_final_word: bool, total_unit: Unit, out: &Output, total_length: usize, rand_index: &mut impl FnMut(usize) -> usize) -> u16 {
	if at_final_word {
		// For the Words unit's final real word, prefer a successor that ends a sentence
		let enders: Vec<u16> = followers.iter().copied().filter(|&w| word(w).ends_with(SENTENCE_ENDERS)).collect();
		if !enders.is_empty() {
			return enders[rand_index(enders.len())];
		}
	}

	if total_unit == Unit::Characters {
		// Prefer a successor whose emission fits the remaining character budget so the chain
		// can land closer to the exact target without needing truncation
		let remaining = total_length.saturating_sub(out.output.len());
		let fits: Vec<u16> = followers.iter().copied().filter(|&w| emission_byte_cost(word(w), &out.output) <= remaining).collect();
		if !fits.is_empty() {
			return fits[rand_index(fits.len())];
		}
	}

	followers[rand_index(followers.len())]
}

/// Byte cost of emitting `token` into `output`, accounting for the preceding space
/// (or lack of it after a '\n' paragraph break or at the start of output).
fn emission_byte_cost(token: &str, output: &str) -> usize {
	let space_len = if output.is_empty() || output.ends_with('\n') { 0 } else { 1 };
	space_len + token.len()
}

/// Try to push a token. Returns false if the emission would exceed the Characters budget
/// (in which case the token is truncated to fit exactly). For other units the caller handles
/// the stop condition at the top of each loop iteration.
fn try_push_token(out: &mut Output, token: &str, total_length: usize, total_unit: Unit) -> bool {
	if total_unit == Unit::Characters {
		let cost = emission_byte_cost(token, &out.output);
		let remaining = total_length.saturating_sub(out.output.len());

		if cost <= remaining {
			out.push_token(token);
			return out.output.len() < total_length;
		}

		// Doesn't fit: truncate what we can of this token, then stop
		let space_len = if out.output.is_empty() || out.output.ends_with('\n') { 0 } else { 1 };
		if remaining > space_len {
			if space_len > 0 {
				out.output.push(' ');
			}
			let budget_for_word = remaining - space_len;
			let end = token.floor_char_boundary(budget_for_word);
			let truncated = &token[..end];
			out.output.push_str(truncated);
			out.words += 1;
			if truncated.ends_with(SENTENCE_ENDERS) {
				out.sentences += 1;
			}
		}
		return false;
	}

	out.push_token(token);
	true
}

// =================
// Paragraph breaks
// =================

/// Samples a paragraph length (in sentences) using rejection sampling from a truncated
/// distribution with a hard cap at 10 sentences. The first sentence has a 1/10 chance of
/// being a single-sentence paragraph; from the second sentence onward, each has a 1/3 chance
/// of ending the paragraph (geometric with p=1/3). Samples exceeding 10 are rejected and
/// resampled, producing a monotonically decreasing PMF with no bump at the cap.
/// Mean ≈ 3.5, median = 3. Reroll probability is ~1.7%.
fn sample_paragraph_length(rand_index: &mut impl FnMut(usize) -> usize) -> usize {
	loop {
		// Single-sentence paragraph: 1/10 chance
		if rand_index(10) == 0 {
			return 1;
		}

		// Geometric(1/3) starting from sentence 2
		let mut length = 1;
		loop {
			length += 1;
			if rand_index(3) == 0 {
				break;
			}
		}

		// Reject samples beyond the cap to avoid a probability bump at 10
		if length <= 10 {
			return length;
		}
	}
}

// ============
// Finalization
// ============

/// Ensures the output ends at a clean sentence boundary before restarting the chain at a
/// dead end. Strips trailing non-sentence punctuation (commas, semicolons, etc.) so we
/// never produce artifacts like ",." then appends a period.
fn ensure_sentence_end(out: &mut Output) {
	if !out.output.is_empty() && !out.output.ends_with(SENTENCE_ENDERS) && !out.output.ends_with('\n') {
		let trimmed_len = out.output.trim_end_matches(|c: char| c.is_ascii_punctuation()).len();
		out.output.truncate(trimmed_len);
		out.output.push('.');
		out.sentences += 1;
		out.sentences_in_current_paragraph += 1;
	}
}

/// Truncate output if it already exceeds the target in the given unit.
/// Only called when the opener alone overshoots; normal continuation flow avoids overshoot.
fn truncate_to_target(out: &mut Output, total_length: usize, total_unit: Unit) {
	match total_unit {
		Unit::Characters => {
			if out.output.len() > total_length {
				let end = out.output.floor_char_boundary(total_length);
				out.output.truncate(end);
			}
		}
		Unit::Words => {
			let mut word_count = 0;
			let mut split = out.output.len();
			for (idx, ch) in out.output.char_indices() {
				if ch == ' ' || ch == '\n' {
					word_count += 1;
					if word_count >= total_length {
						split = idx;
						break;
					}
				}
			}
			out.output.truncate(split);
		}
		Unit::Sentences => {
			let mut sentences_seen = 0;
			let mut byte_cursor = 0_usize;
			let mut split = out.output.len();
			while byte_cursor < out.output.len() {
				let remaining = &out.output[byte_cursor..];
				let next_ws = remaining.find([' ', '\n']).unwrap_or(remaining.len());
				let word_bytes = &remaining[..next_ws];
				if word_bytes.ends_with(SENTENCE_ENDERS) {
					sentences_seen += 1;
					if sentences_seen >= total_length {
						split = byte_cursor + next_ws;
						break;
					}
				}
				byte_cursor += next_ws + if next_ws < remaining.len() { 1 } else { 0 };
			}
			out.output.truncate(split);
		}
		Unit::Paragraphs => {
			let mut paragraphs_seen = 0;
			let mut split = out.output.len();
			for (idx, ch) in out.output.char_indices() {
				if ch == '\n' {
					paragraphs_seen += 1;
					if paragraphs_seen >= total_length {
						split = idx;
						break;
					}
				}
			}
			out.output.truncate(split);
		}
	}
}

/// Enforce unit-specific ending guarantees on the final output string.
fn apply_endgame(output: &mut String, total_unit: Unit) {
	if output.is_empty() {
		return;
	}

	match total_unit {
		Unit::Words => {
			// Guarantee the output ends with a sentence-ender. If the last word does not,
			// strip trailing non-sentence punctuation (commas, dashes, semicolons) and append '.'
			if !output.ends_with(SENTENCE_ENDERS) {
				let trimmed_len = output.trim_end_matches(|c: char| c.is_ascii_punctuation()).len();
				output.truncate(trimmed_len);
				output.push('.');
			}
		}
		Unit::Characters => {
			// Substitute the final character with '.' to stay within the exact byte budget.
			// Unlike Words mode, we don't strip trailing punctuation first because that would
			// shrink the output below the requested character count
			if !output.ends_with(SENTENCE_ENDERS) {
				if let Some(last_char) = output.chars().next_back() {
					let last_idx = output.len() - last_char.len_utf8();
					output.truncate(last_idx);
				}
				output.push('.');
			}
		}
		Unit::Sentences | Unit::Paragraphs => {
			// These units complete at a sentence boundary or paragraph break by construction
		}
	}
}

// ============
// Chain lookup
// ============

/// Retrieves the word string for a given vocabulary index using the compact offset table.
fn word(index: u16) -> &'static str {
	let start = WORD_OFFSETS[index as usize] as usize;
	let end = WORD_OFFSETS[index as usize + 1] as usize;
	&WORD_DATA[start..end]
}

/// Resolves a STARTERS entry (a u16 index) back to its (word_a, word_b) bigram pair.
/// Indices in `[0..SINGLE_KEYS.len())` refer to single-successor bigrams;
/// indices in `[SINGLE_KEYS.len()..)` refer to multi-successor bigrams.
fn starter_bigram(starter_index: u16) -> (u16, u16) {
	let i = starter_index as usize;
	let key = if i < SINGLE_KEYS.len() { SINGLE_KEYS[i] } else { MULTI_KEYS[i - SINGLE_KEYS.len()] };
	((key >> 16) as u16, key as u16)
}

/// Looks up the slice of word indices that may follow the given bigram.
/// Checks the single-successor table first (89% of bigrams), then the multi-successor table.
fn successors_of(word_a: u16, word_b: u16) -> &'static [u16] {
	let key = (word_a as u32) << 16 | word_b as u32;
	if let Ok(i) = SINGLE_KEYS.binary_search(&key) {
		std::slice::from_ref(&SINGLE_VALUES[i])
	} else if let Ok(i) = MULTI_KEYS.binary_search(&key) {
		&SUCCESSORS[MULTI_STARTS[i] as usize..MULTI_STARTS[i + 1] as usize]
	} else {
		&[]
	}
}

// ==========
// Unit tests
// ==========

#[cfg(test)]
mod tests {
	use super::*;

	fn deterministic_rng(seed: u64) -> impl FnMut(usize) -> usize {
		let mut state = seed;
		move |n| {
			// Simple LCG for deterministic tests
			state = state.wrapping_mul(6364136223846793005).wrapping_add(1);
			(state >> 33) as usize % n
		}
	}

	// ---- Word count ----

	#[test]
	fn words_count_matches_requested() {
		// Minimum is 2 words since chain seeding always emits a bigram (two words)
		for count in [2, 5, 10, 25, 50, 100] {
			let text = generate(0, Unit::Words, count, Unit::Words, deterministic_rng(42));
			let actual = text.split_whitespace().count();
			assert_eq!(actual, count, "requested {count} words, got {actual}: {text:?}");
		}
	}

	#[test]
	fn words_end_with_sentence_ender() {
		for seed in 0..20 {
			let text = generate(0, Unit::Words, 30, Unit::Words, deterministic_rng(seed));
			assert!(text.ends_with(SENTENCE_ENDERS), "seed {seed}: output should end with sentence-ender: {text:?}");
		}
	}

	// ---- Sentence count ----

	#[test]
	fn sentences_count_matches_requested() {
		for count in [1, 3, 5] {
			let text = generate(0, Unit::Words, count, Unit::Sentences, deterministic_rng(42));
			let actual = text.chars().filter(|&c| c == '.' || c == '!' || c == '?').count();
			assert_eq!(actual, count, "requested {count} sentences, got {actual}: {text:?}");
		}
	}

	// ---- Paragraph count ----

	#[test]
	fn paragraphs_count_matches_requested() {
		for count in [1, 2, 3, 5] {
			let text = generate(0, Unit::Words, count, Unit::Paragraphs, deterministic_rng(42));
			let actual = text.matches('\n').count() + 1;
			assert_eq!(actual, count, "requested {count} paragraphs, got {actual}: {text:?}");
		}
	}

	#[test]
	fn paragraphs_no_trailing_newline() {
		for seed in 0..10 {
			let text = generate(0, Unit::Words, 3, Unit::Paragraphs, deterministic_rng(seed));
			assert!(!text.ends_with('\n'), "seed {seed}: output should not end with newline: {text:?}");
		}
	}

	// ---- Character count ----

	#[test]
	fn characters_count_matches_requested() {
		for count in [10, 50, 100, 200, 500] {
			let text = generate(0, Unit::Words, count, Unit::Characters, deterministic_rng(42));
			assert_eq!(text.len(), count, "requested {count} chars, got {}: {text:?}", text.len());
		}
	}

	#[test]
	fn characters_end_with_sentence_ender() {
		for seed in 0..20 {
			let text = generate(0, Unit::Words, 100, Unit::Characters, deterministic_rng(seed));
			assert!(text.ends_with(SENTENCE_ENDERS), "seed {seed}: output should end with sentence-ender: {text:?}");
		}
	}

	// ---- Opener ----

	#[test]
	fn opener_words_prefix_matches_classic() {
		let text = generate(8, Unit::Words, 50, Unit::Words, deterministic_rng(42));
		assert!(text.starts_with("Lorem ipsum dolor sit amet, consectetur adipiscing elit,"), "opener mismatch: {text:?}");
	}

	#[test]
	fn opener_paragraph_break() {
		let text = generate(1, Unit::Paragraphs, 3, Unit::Paragraphs, deterministic_rng(42));
		let paragraphs: Vec<&str> = text.split('\n').collect();
		assert_eq!(paragraphs.len(), 3, "expected 3 paragraphs: {text:?}");
		assert!(paragraphs[0].starts_with("Lorem ipsum"), "first paragraph should be classic text: {text:?}");
	}

	#[test]
	fn opener_characters_exact_length() {
		for char_count in [10, 30, 50, 100] {
			let text = generate(char_count, Unit::Characters, 500, Unit::Characters, deterministic_rng(42));
			assert!(text.starts_with(&CLASSIC_LOREM_IPSUM_TEXT[..CLASSIC_LOREM_IPSUM_TEXT.floor_char_boundary(char_count)]));
		}
	}

	// ---- Edge cases ----

	#[test]
	fn zero_total_returns_empty() {
		let text = generate(8, Unit::Words, 0, Unit::Words, deterministic_rng(42));
		assert!(text.is_empty(), "zero total should return empty: {text:?}");
	}

	#[test]
	fn zero_opener_no_classic_text() {
		let text = generate(0, Unit::Words, 20, Unit::Words, deterministic_rng(42));
		assert!(!text.starts_with("Lorem"), "zero opener should not start with Lorem: {text:?}");
	}

	#[test]
	fn no_double_spaces() {
		for seed in 0..20 {
			let text = generate(0, Unit::Words, 100, Unit::Words, deterministic_rng(seed));
			assert!(!text.contains("  "), "seed {seed}: double space found in: {text:?}");
		}
	}

	#[test]
	fn no_punctuation_before_period_artifacts() {
		for seed in 0..50 {
			let text = generate(0, Unit::Words, 200, Unit::Words, deterministic_rng(seed));
			// The corpus contains words ending in , ; : which should be stripped before forced periods
			assert!(!text.contains(",."), "seed {seed}: ',.' artifact in: {text:?}");
			assert!(!text.contains(";."), "seed {seed}: ';.' artifact in: {text:?}");
			assert!(!text.contains(":."), "seed {seed}: ':.' artifact in: {text:?}");
		}
	}

	#[test]
	fn capitalization_after_sentence_ender() {
		for seed in 0..20 {
			let text = generate(0, Unit::Words, 100, Unit::Words, deterministic_rng(seed));
			let chars: Vec<char> = text.chars().collect();
			for i in 0..chars.len().saturating_sub(2) {
				if (chars[i] == '.' || chars[i] == '!' || chars[i] == '?') && chars[i + 1] == ' ' {
					assert!(
						chars[i + 2].is_uppercase(),
						"seed {seed}: expected capital after sentence-ender at position {i}: ...{}...",
						&text[text.floor_char_boundary(i.saturating_sub(5))..text.floor_char_boundary(i + 10)]
					);
				}
			}
		}
	}

	#[test]
	fn capitalization_after_paragraph_break() {
		for seed in 0..10 {
			let text = generate(0, Unit::Words, 3, Unit::Paragraphs, deterministic_rng(seed));
			for (i, paragraph) in text.split('\n').enumerate() {
				let first_char = paragraph.chars().next().unwrap_or(' ');
				assert!(first_char.is_uppercase(), "seed {seed}: paragraph {i} should start with capital: {paragraph:?}");
			}
		}
	}

	// ---- Stability ----

	#[test]
	fn deterministic_output() {
		let text1 = generate(8, Unit::Words, 50, Unit::Words, deterministic_rng(42));
		let text2 = generate(8, Unit::Words, 50, Unit::Words, deterministic_rng(42));
		assert_eq!(text1, text2, "same seed should produce identical output");
	}

	#[test]
	fn different_seeds_differ() {
		let text1 = generate(0, Unit::Words, 50, Unit::Words, deterministic_rng(1));
		let text2 = generate(0, Unit::Words, 50, Unit::Words, deterministic_rng(2));
		assert_ne!(text1, text2, "different seeds should produce different output");
	}

	#[test]
	fn opener_overshoots_total() {
		// Opener requests 100 words but total is only 10 — should truncate to 10
		let text = generate(100, Unit::Words, 10, Unit::Words, deterministic_rng(42));
		let actual = text.split_whitespace().count();
		assert_eq!(actual, 10, "opener overshoot should truncate to total: got {actual} words in {text:?}");
	}

	#[test]
	fn single_word_output() {
		// Chain seeding emits a bigram (2 words minimum), so requesting 1 word produces 2
		let text = generate(0, Unit::Words, 1, Unit::Words, deterministic_rng(42));
		let actual = text.split_whitespace().count();
		assert_eq!(actual, 2, "single-word request should produce 2 words (bigram minimum): got {actual} in {text:?}");
		assert!(text.ends_with(SENTENCE_ENDERS), "output should end with sentence-ender: {text:?}");
	}

	#[test]
	fn large_character_count() {
		// Exercises the saturating_mul guard on max_iterations
		let text = generate(0, Unit::Words, 10_000, Unit::Characters, deterministic_rng(42));
		assert_eq!(text.len(), 10_000, "large character count should produce exact length");
		assert!(text.ends_with(SENTENCE_ENDERS), "output should end with sentence-ender: {text:?}");
	}
}
