[package]
name = "cargo-run-internal-watch"
# Inherited from workspace - start
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true
# Inherited from workspace - end

[dependencies]
cargo-run = { path = "../.." }
notify = "8.2.0"
notify-debouncer-full = "0.7.0"
