[package]
name = "graphite-desktop-platform-mac"
version = "0.1.0"
description = "Graphite Desktop Platform Mac"
authors = ["Graphite Authors <contact@graphite.rs>"]
license = "Apache-2.0"
repository = ""
edition = "2024"
rust-version = "1.87"

[features]
default = ["bundle"]
bundle = ["dep:serde", "dep:plist"]
app = ["dep:graphite-desktop"]
helper = ["dep:graphite-desktop"]

[dependencies]
graphite-desktop = { path = "../..", optional = true }
serde = { workspace = true, optional = true }
plist = { version = "*", optional = true }
