[package]
name = "graphite-desktop-platform-mac"
description = "Graphite Desktop Platform Mac"
# Inherited from workspace - start
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true
# Inherited from workspace - end

[features]
main = ["dep:graphite-desktop"]
helper = ["dep:graphite-desktop-ui"]

[[bin]]
name = "graphite"
path = "src/main.rs"
required-features = ["main"]

[[bin]]
name = "helper"
path = "src/helper.rs"
required-features = ["helper"]

[dependencies]
graphite-desktop = { path = "../..", optional = true }
graphite-desktop-ui = { path = "../../ui", optional = true }
