[target.wasm32-unknown-unknown]
rustflags = [
	# Currently disabled because of https://github.com/GraphiteEditor/Graphite/issues/1262
	# The current simd implementation leads to undefined behavior
	#"-C",
	#"target-feature=+simd128",
	"-C",
	"target-feature=+bulk-memory",
	"-C",
	"link-arg=--max-memory=4294967296",
	"--cfg=web_sys_unstable_apis",
	# TODO: Remove this and find a better way to stay within the 25MB limit of cloudflare pages
	"-C",
	"opt-level=s",
]

[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
