[package]
name = "tag-derive"
version = "0.0.1"
edition = "2021"
authors = ["Graphite Authors <contact@graphite.rs>"]
description = "Derive macro for the Tag trait in raw-rs"
license = "MIT OR Apache-2.0"
readme = "../README.md"
repository = "https://github.com/GraphiteEditor/Graphite/tree/master/libraries/raw-rs/tag-derive"
documentation = "https://docs.rs/tag-derive"

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn.workspace = true
