[package]
name = "brush-nodes"
description = "Brush rendering nodes for Graphene"
# Inherited from workspace - start
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true
# Inherited from workspace - end

[features]
default = ["serde"]
serde = ["dep:serde", "core-types/serde", "raster-types/serde"]

[dependencies]
# Local dependencies
dyn-any = { workspace = true }
brush-types = { workspace = true }
core-types = { workspace = true }
graphene-hash = { workspace = true }
graphic-types = { workspace = true }
raster-types = { workspace = true, features = ["wgpu"] }
wgpu-executor = { workspace = true }
node-macro = { workspace = true }

# Workspace dependencies
glam = { workspace = true }
half = { workspace = true }
bytemuck = { workspace = true }
wgpu = { workspace = true }

# Optional workspace dependencies
serde = { workspace = true, optional = true, features = ["derive"] }

[dev-dependencies]
# Workspace dependencies
tokio = { workspace = true }
