[package]
name = "math-parser"
description = "Parser for Graphite style mathematics expressions"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
thiserror = "2.0"
num-complex = "0.4"
chumsky = { version = "0.10", default-features = false, features = ["std"] }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "bench"
harness = false
