name: "Build Nix Package"

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 📥 Clone repository
        uses: actions/checkout@v4

      - name: ❄ Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: 💾 Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: 📦 Build Nix package dev
        run: nix build .#graphite-dev --print-build-logs
