name: "Library: Raw-rs"

on:
  push:
    branches:
      - master
    paths:
      - "libraries/raw-rs/**"
  pull_request:
    branches:
      - master
    paths:
      - "libraries/raw-rs/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      RUSTC_WRAPPER: /usr/bin/sccache
      CARGO_INCREMENTAL: 0
      SCCACHE_DIR: /var/lib/github-actions/.cache

    steps:
      - name: 📥 Clone and checkout repository
        uses: actions/checkout@v3

      - name: 🦀 Install the latest Rust
        run: |
          echo "Initial system version:"
          rustc --version
          rustup update stable
          echo "Latest updated version:"
          rustc --version

      - name: 🔬 Check Rust formatting
        run: |
          cd libraries/raw-rs
          mold -run cargo fmt --all -- --check

      - name: 🦀 Build Rust code
        run: |
          cd libraries/raw-rs
          mold -run cargo build --release --all-features

      - name: 🧪 Run Rust tests
        run: |
          cd libraries/raw-rs
          mold -run cargo test --release --all-features
