name: "Provide Shaders"

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: 📥 Clone repository
        uses: actions/checkout@v6

      - name: ❄ Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: 💾 Set up Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: 🏗 Build graphene raster nodes shaders
        run: nix build .#graphite-raster-nodes-shaders && cp result raster_nodes_shaders_entrypoint.wgsl

      - name: 📤 Upload graphene raster nodes shaders to artifacts repository
        run: |
          bash .github/workflows/scripts/artifact-upload.bash \
            ${{ vars.ARTIFACTS_REPO_OWNER }} \
            ${{ vars.ARTIFACTS_REPO_NAME }} \
            ${{ vars.ARTIFACTS_REPO_BRANCH }} \
            rev/${{ github.sha }}/raster_nodes_shaders_entrypoint.wgsl \
            raster_nodes_shaders_entrypoint.wgsl \
            "${{ github.sha }} raster_nodes_shaders_entrypoint.wgsl" \
            ${{ secrets.ARTIFACTS_REPO_TOKEN }}
